# Configuration items for Github page
# - Jan 8, 2024 -- added Jekyll theme
#remote_theme: pages-themes/time-machine@v0.2.0
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: MDW - SNHU - CS-499

description: The information found on this page will present a professional portfolio of updated 
and improved projects coded for various SNHU computer science courses.  The final result
will fulfill the requirements for the SNHU Computer Science Capstone course CS-499

show_downloads: false
