# Configuration items for Github page
# - Jan 8, 2024 -- added Jekyll theme
#remote_theme: pages-themes/time-machine@v0.2.0
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
title: [The title of your site]
description: [A short description of your site's purpose]

show_downloads: false
